---
- name: NAS Infrastructure
  hosts: nas
  become: yes
  roles:
    - nas_base
    - nas_storage
    - nas_backups
    - nas_docker

- name: Desktop Infrastructure
  hosts: desktops
  become: yes
  roles:
    - desktop_base
