---
- name: Update apt cache and upgrade system
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install essential base packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - git
      - vim
      - btop
      - tmux
      - jq
      - sqlite3
      - btrfs-progs
      - hdparm
      - rclone
      - restic
      - inotify-tools
      - rsync
      - sudo
      - ufw
      - fail2ban
      - zsh
      - fzf
      - zoxide
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present

- name: Configure DNS resolution (resolv.conf)
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      domain fritz.box
      search fritz.box
      nameserver 192.168.178.1
    mode: '0644'
    owner: root
    group: root

- name: Install Docker and Docker Compose
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is running and enabled
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Change kevin default shell to zsh
  ansible.builtin.user:
    name: kevin
    shell: /usr/bin/zsh

- name: Deploy .zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: /home/kevin/.zshrc
    owner: kevin
    group: kevin
    mode: '0644'
- name: Add NVIDIA Container Toolkit GPG key
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.asc
    mode: '0644'

- name: Add NVIDIA Container Toolkit repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.asc] https://nvidia.github.io/libnvidia-container/stable/deb/amd64 /"
    state: present
    filename: nvidia-container-toolkit

- name: Install NVIDIA and CUDA dependencies
  ansible.builtin.apt:
    name:
      - nvidia-container-toolkit
      - libcuda1
    state: present
    update_cache: yes

- name: Configure Docker to use NVIDIA runtime
  ansible.builtin.command: nvidia-ctk runtime configure --runtime=docker
  register: nvidia_ctk_result
  changed_when: "'Configured' in nvidia_ctk_result.stdout"
  notify: Restart Docker
