#SPDX-License-Identifier: MIT-0
---
# handlers file for nas_base

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
